name: trivy-scan

on:
   workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy CLI
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: 'latest'

      - name: Print Trivy version
        run: trivy --version

      - name: Scan repository for vulnerabilities
        run: trivy fs . --severity HIGH,CRITICAL --exit-code 1
