name: trivy-scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # התקנת Trivy CLI ישירות מול הסקריפט הרשמי
      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Print Trivy version
        run: trivy --version

      - name: Scan repository for vulnerabilities
        run: trivy fs . --severity HIGH,CRITICAL --exit-code 1